#Base Container 
FROM rust:1.82.0

RUN apt update && apt install -y net-tools netcat-openbsd curl wget iputils-ping

#Add the cargo to the PATH
RUN echo "export PATH=$PATH:/usr/local/cargo/bin" >> /root/.bashrc
#Install the rust tools we want
RUN rustup target add wasm32-unknown-unknown
RUN cargo install trunk cargo-watch
RUN cargo install sea-orm-cli

