.PHONY: all build run

# Default target to run when `make` is called without arguments
all: build

# Build the project
build:
	go build -o bin/k3sClient cmd/main.go

# Run the project
run:
	go run ./cmd/main.go
